### ISSUE TITLE
[Feature request] Instead of item, run a command as console.

### ISSUE THREAD

**Issue by mrfloris** [WeNeedCoffee/FoundDiamonds#1]
FD has the ability to reward someone (or all) with a (random) item. On our setup we have for example ancient scrolls and other unique items that we want to very rarely drop. 

It would be rather fantastic if there's a really low % chance of it doing so. We have them as a kit with CMI. 

If FD could execute a command instead of rewarding an item, and run that as a console command. Then we can give the player the kit very rarely.

we would run `cmi kit scroll1 %player%`

I hope I am making sense.

**Comment by mrfloris** [comment]
I see there's been some updates on this in July, has it ever been finished btw ? Just curious!

**Comment by Dalethium** [comment]
https://github.com/WeNeedCoffee/FoundDiamonds/releases/tag/4.0.3-SNAPSHOT
Literally, no clue if this is entirely broken or not, but I had a spare moment and figured I'd spend a few working on this. No promises that this is not a broken build so please use it in a test environment first.

**Comment by mrfloris** [comment]
Thank you, will test. Appreciate the help.

**Comment by Dalethium** [comment]
> Thank you, will test. Appreciate the help.

Did you ever give this a shot?

**Comment by mrfloris** [comment]
Yes, thank you.

**Comment by Dalethium** [comment]
Marking as closed since this is done
