### ISSUE TITLE
[Feature] More control over broadcasts

### ISSUE THREAD

**Issue by mrfloris** [WeNeedCoffee/FoundDiamonds#2]
Right now FD fantastically announces who has found something. Especially to Discord. Thank you for this addition in 1.16.x

It would be nice if there's a tiny bit more control over who gets what.

`fd.broadcast` requires us to add it to default group, so it goes to discord.

What we want:

- Always announce it on discord
- Only announce it to operators, or people who have `fd.announce`
- Ability to give everybody `fd.broadcast`, but not display it in-game? (toggle in config.yml maybe?) (or a separate permission for discord to announce when someone from that group found something?)

**Comment by Dalethium** [comment]
https://www.spigotmc.org/resources/founddiamonds-updated.81124/update?update=346290 give this a try, let me know how it goes :)
